# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e74d76e926096e1d3a56d80e765b9e02f8b757960ab8ad6d2435b7e7119873015b59b9d046bb037978b0e3182fc14f428739a333465d8b17047998d2357fc52

test:
  secret_key_base: 01d36d4044bfd7ad19b257c3acb0a45dd004519b942e0b2da3a3acf0689a78e1ee55e104e62ae804038f49a8e84883a77758358868abd9f9b1e828670235f571

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
